### ISSUE TITLE
Missing MyPy compatible type annotations

### ISSUE THREAD

**Issue by StarringLara** [coinbase/coinbase-advanced-py#26]
Hello. It seems like there are no MyPy compatible type annotations provided by this package. Is that correct? IMO this is really important to support. If I run mypy on my code, it shows `error: Skipping analyzing "coinbase": module is installed, but missing library stubs or py.typed marker  [import-untyped]` as well as `note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports`. If types are provided, and I'm just not using them right I will seek help elsewhere, I just wanted to get clarity on if they are provided or not and request that this be added if they are not.

I also believe it is important not just to provide a best guess of type stubs but to actually use types internally in the project and have them automatically statically validated to help keep them as accurate as possible.

**Comment by StarringLara** [comment]
Pull request #27 is the kind of thing I'm suggesting, but throughout the entire project.

**Comment by urischwartz-cb** [comment]
@StarringLara Thank you so much for flagging this! We will look into adding MyPy annotations soon and will update you once that is done. Thanks!

**Comment by urischwartz-cb** [comment]
@StarringLara Please note that we do have type annotations for all parameters to our public functions. You are right that we have not added type annotations to the return types and will work on adding that soon. Hopefully the existing param types are useful for you regardless!

**Comment by StarringLara** [comment]
Certainly the existing types are appreciated. I am just getting started with using this SDK, and as I get further with it, I am noticing some type hints in the code, and I do find those very helpful. In a certain sense, it's definitely not an all or nothing thing, and I appreciate any types you are able to provide or add. In another sense, I hope you won't dismiss the concept that the ideal is to have types everywhere, treating it as requiring everything to be typed from then on. Of course, the ideal should not hold you back from making incremental progress now, nor does it make that progress unappreciated. As far as I understand it, the best way to eventually enforce the ideal would be for you to use mypy internally as your own QA tool for this project, and to require it to report no issues in your CI tests, while using it with the setting `strict = true`, which I think will require all parameters and return values to have a type.

**Comment by urischwartz-cb** [comment]
@StarringLara we just pushed a new v1.1.3 that includes fully annotated return types for all of our exposed functions. Hopefully that helps in your development. Please let us know if you have any other questions or recommendations for our SDK.
Thanks for your feedback and for helping us improve our product!
