### ISSUE TITLE
Package available on conda-forge

### ISSUE THREAD

**Issue by MementoRC** [coinbase/coinbase-advanced-py#41]
FYI, this library is now available on conda-forge. Should anyone on your team desire to be added as a maintainer, just let me know
https://github.com/conda-forge/coinbase-advanced-py-feedstock

**Comment by urischwartz-cb** [comment]
Thank you! Is there any action that we need to take here?

**Comment by MementoRC** [comment]
Note that we skipped a few revisions because the recipe was based of 1.1.3 and its source link had an extra `.` in `v.1.1.3`, so the automation failed to pick-up on the correct `v1.2.2` syntax until I noticed it. I don't check on the upstreams so regularly, so having someone from you team overseeing that the automated releases happen when expected  would be beneficial for all

For example, you make a new release and a day after there is still no conda release notification, then something unexpected happened and you could ping me with an `Issue` in the package feedstock, or fix it, since you would have maintainer privilege

**Comment by MementoRC** [comment]
The recipe was updated to v1.3.0 - If you want to add a maintainer to the feedstock, you can do so at any time at:
https://github.com/conda-forge/coinbase-advanced-py-feedstock/issues/new?assignees=&labels=&projects=&template=2-bot-commands.yml
with the subject:
`@conda-forge-admin, please add user @<github name>`
