### ISSUE TITLE
paper trading

### ISSUE THREAD

**Issue by BuildWithData** [coinbase/coinbase-advanced-py#52]
could not find any docs about paper trading, is it available ? if not, do you plan to make it available ?

**Comment by urischwartz-cb** [comment]
Hi @BuildWithData , we currently do not offer paper trading/sandbox environment, but it is on our roadmap. For now, hopefully our available APIs are sufficient for testing your code. As mentioned above, we encourage you to use our Discord to ask any API related questions there. Thanks!

**Comment by djflux** [comment]
Comment from someone 03 Jan 2025 at 0720 ET in the Coinbase Discord regarding a sandbox for the REST API:

> Rishabh Jain — Today at 7:20 AM
> Hi @Warix3, thanks for reaching out.
> 
> We do have a static sandbox environment for Advanced trade API but only Accounts and Orders related endpoints are currently available in the sandbox. - you may try this.

Looks like the sandbox recently got implemented: https://docs.cdp.coinbase.com/advanced-trade/docs/rest-api-sandbox
