### ISSUE TITLE
get_candles throttling returns "401 Unauthorized" instead of "Too Many Requests"

### ISSUE THREAD

**Issue by angelaponte** [coinbase/coinbase-advanced-py#60]
Greetings, thank you for the awesome package, great product, and services!

I implemented a Python function that uses get_candles() to pull historic data, 299 candles at a time, and throttles itself based on public rate limits.

This week, when pulling data, I started getting this error:
HTTPError: 401 Client Error: Unauthorized Unauthorized

This was unexpected and I created a new API key as a result (unnecessarily; both API keys work), even though I'm invoking the public API; I normally get a "Too Many Requests" error when Coinbase needs me to dial it down to make room for large request volume on the exchange, beyond the publicly posted rate limits.

This morning, I added an exponential backoff whenever I get the "401 Unauthorized" exception, tried to pull the data, and it worked; I now have a full dataframe, like I did before this arose. My sense is that exponential backoff is a thoughtful way to protect resources.

It was confusing to get an "Unauthorized" message when "Too Many Requests" is expected and more accurate when Coinbase needs to throttle customers to conserve resources due to high volume on the exchange.

**Comment by justinsogoni-cb** [comment]
Hi, are you using the get_candles() endpoint or the get_public_candles() endpoint from the SDK?

**Comment by angelaponte** [comment]
Thanks for the question; I'm using the get_candles() endpoint.

**Comment by benjzyq** [comment]
Hi, I got the similar problem. I tried to use list_orders and get_orders and it would randomly throw out 401 error, like, 2 out of 5 times.

**Comment by urischwartz-cb** [comment]
This is resolved now. Please let us know on Discord if you continue seeing issues. Thanks for raising!
