### ISSUE TITLE
websocket authentication fails

### ISSUE THREAD

**Issue by kujbika** [coinbase/coinbase-advanced-py#64]
The issue im facing is that according to the coinbase api docs (https://docs.cdp.coinbase.com/exchange/docs/websocket-auth#examples), I would need a passphrase to authenticate myself subscribing to the full websocket channel. However, the package doesnt allow me to set a passphrase. 
Using only the api key and the api secret results in authentication failure. 

code: 
```python
from coinbase import WSClient

api_key = "..."
api_secret = "..."

def on_message(msg):
    print(msg)

def on_open():
    print("Connection opened!")

client = WSClient(api_key=api_key, api_secret=api_secret, on_message=on_message, on_open=on_open)
client.open()
client.subscribe(product_ids=["BTC-USD", "ETH-USD"], channels=["full"])
client.run_forever_with_exception_check()
```

stdout:
Connection opened!
{"type":"error","message":"authentication failure"}

**Comment by urischwartz-cb** [comment]
Hi, the docs that you referenced are for the Exchange Websocket API.
This SDK is built for the Advanced Trade Websocket API. Docs here: https://docs.cdp.coinbase.com/advanced-trade/docs/ws-auth

Are you using CDP keys? (details [here](https://docs.cdp.coinbase.com/advanced-trade/docs/getting-started/)). Exchange keys will not work here.
