### ISSUE TITLE
Open api spec for advanced api

### ISSUE THREAD

**Issue by pankajpreet** [coinbase/coinbase-advanced-py#72]
Coinbase advanced API SDK is only available for Python. If Coinbase provides open API spec for all advanced APIs, it will be straightforward to implement advanced API in other languages like Go and Java.

**Comment by urischwartz-cb** [comment]
Hi @pankajpreet, we will look into the Open API spec.
In the meantime, we now have sample SDKs in Go and Java and Typescript, which should help get you started: 

- Go: https://github.com/coinbase-samples/advanced-trade-sdk-go
- Java: https://github.com/coinbase-samples/advanced-sdk-java
- Typescript: https://github.com/coinbase-samples/advanced-sdk-ts
