### ISSUE TITLE
Get fees rates and 30 days trailing volume

### ISSUE THREAD

**Issue by christoschronopoulos** [coinbase/coinbase-advanced-py#75]
Hi all, 
I am using the python REST Client and load the credentials from the CDP JSON file, so I can successfully get the accounts as follows.
`input_filename = "cdp_api_key.json"
client = RESTClient(key_file=input_filename)
accounts = client.get_accounts()`

However, when I try to get the fees and trailing volume information I get a 401 Unauthorised error
`fees = client.get("/api/v3/brokerage/fees")
print(fees)`

I took a look in the documentation [https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_getfees](url) but I cannot figure out what I am missing. I hope you can help me.

**Comment by urischwartz-cb** [comment]
Hi, thanks for reaching out. The Fees API you are referencing there is the Exchange API, which uses the api.exchange.coinbase.com. This SDK is for the Advanced Trade API (docs [here](https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_gettransactionsummary)) which uses the api.coinbase.com domain. 

Possibly the Get Transaction Summary endpoint there will be useful to you.
