### ISSUE TITLE
get_portfolio_breakdown() permission error on non-default portfolios

### ISSUE THREAD

**Issue by smbrandonjr** [coinbase/coinbase-advanced-py#89]
I am receiving the error: {"error":"PERMISSION_DENIED","error_details":"User does not have access to portfolio","message":"User does not have access to portfolio"} when executing get_portfolio_breakdown(uuid) for a portfolio that is not the default portfolio.

API key has trade, transfer and view permissions. 

coinbase-advanced-py version 1.8.2

**Comment by xiaofeihuang-cb** [comment]
This is API specific question. Could you please raise the question in the [discord channel](https://discord.com/channels/1220414409550336183/1220464268743278613).
Please follow [this](https://discord.com/invite/cdp) to join the discord community if you haven't. thanks
